#!/usr/bin/env bash
# vim: filetype=bash

###############################################################################
#                        MHYM CONFIGURATION


#--------------DWM-SETTINGS------------------
# system packages required by dwm for installation
DWM_DEP_PACKAGES=(
                "git" # VCS 
                "xorg" # X.ORG Server
                "xorg-dev" # X11 dev deps
                "x11proto-core-dev" # X11 protocol extensions
                "build-essential" # dev dependencies like gcc,make 
              )

# string linking to dwm git repo
# if not set, will be taken in a prompt
# It can be a:
# local git repo, i.e: file://absolute_path_to_git_repo (doesn't have to be git initialized)
# remote git repo, i.e: https://gitlab.com/user/dwm.git
# uri scheme is necessary, i.e: don't forget to include file:// | https://
DWM_URI="https://github.com/Justaus3r/my-dwm.git"

# dwm install make command. excluding ``sudo``, 
# change this if you have changed the ``install`` target in Makefile to something else
DWM_MAKE_CMD="make install"


#TODO: ADD SUPPORT FOR DWM PATCHES

#---------------------------------------------



#-------------DMENU-SETTING-------------------
# dmenu configuration

DMENU_URI="https://github.com/Justaus3r/my-dmenu.git"

DMENU_MAKE_CMD="make install"
#---------------------------------------------



#-----------TERMINAL-EMULATOR-SETTING-----------

# NOTE: For now, this section only includes the package name for terminal emulator. change it to one, that you like

#TODO: #1


TERMINAL_PKG="kitty"

#-----------------------------------------------



#------------XSERVER-SETTING----------------------
#settings for X.ORG server 


# appends a conditional command, to .bash_profile after dwm setup, that starts
# X server if its not running
# set it to false, if you already have it in .bash_profile
EXEC_AT_LOGIN=true

#set this to true ,if you want to overwrite
#.Xresources
OVERWRITE_XRESOURCES=false

#set this to true, if you want to merge
# .Xresources with current settings
MERGE_XRESOURCES=false

#path to .Xresources file
# will only be read if either OVERWRITE_XRESOURCES
# or MERGE_XRESOURCES is true
DOTXRESOURCES_PATH=""

#----------------------------------------------------


#--------------WALLPAPER-SETTING------------------
# utility for setting wallpaper
BG_UTIL="feh"

# command for BG_UTIL
#don't include the image path
UTIL_CMD="--bg-scale "

# uri for background
# can be file:// | https://
# if not set, will be taken in a prompt
# set to nill, for no background 
BACKGROUND_URI="https://raw.githubusercontent.com/D3Ext/aesthetic-wallpapers/refs/heads/main/images/anime_skyline.png"
#-------------------------------------------------


#---------------STATUS-BAR-SETTING----------------
# settings for thytom/dwmbar status-bar

#set to nill, if you don't want to use it
DWMBAR_URI="https://github.com/thytom/dwmbar.git"

#-------------------------------------------------


#--------------POST-INSTALL-SYSTEM-PACAKES------------------
#system packages to install AFTER dwm configuration
POST_INSTALL_SYSTEM_PACAGES=(
                "feh"
                 "systemd-sysv"
                 "xdg-utils"
                 "network-manager"
                 "neovim"
                 "blueman"
                 "pulseaudio"
                 "zip"
                 "unzip"
                 "btop"
                 "curl"
                 )

#------------------------------------------------------------



#---------------MISCELLANEOUS-------------------
#misc settings

# if set,mhym will run in silent mode 
# note: will cause a crash if readline_promt() is called
# while this is set, i.e: don't set it to true, if you haven't
# set all the pre-run configuration options here
NO_PROMPT=false

#-----------------------------------------------





#                        END MHYM CONFIGURATION
################################################################################




set -e

UTILITY_VERSION="0.1.0"
UTILITY_DEPS=( "rev" )

info(){

    if [[ $NO_PROMPT = true ]]; then
        return
    fi

    local prefix_str="\x1b[34m"
    local suffix_str="\x1b[m\n"
    if [[ "$2" = "log" ]];then
        prefix_str="\x1b[32m[INFO]::"
    fi
    printf "%b%b%b" "$prefix_str" "$1" "$suffix_str"
}


warning(){
    if [[ $NO_PROMPT = true ]]; then
        return
    fi
   printf "\x1b[33m[WARNING]::%s\x1b[m\n" "$1"
}

error(){
    if [[ $NO_PROMPT = true ]] && [[ "$2" = "exit-after" ]];then
	exit 1
    elif [[ $NO_PROMPT = true ]]; then
        return
    fi
   printf "\x1b[31m[ERROR]::%s\x1b[m\n" "$1"
   if [[ "$2" = "exit-after" ]]; then
       exit 1
   fi
}

logo_print(){
   info  "███    ███ ██   ██ ██    ██ ███    ███" 
   info  "████  ████ ██   ██  ██  ██  ████  ████" 
   info  "██ ████ ██ ███████   ████   ██ ████ ██" 
   info  "██  ██  ██ ██   ██    ██    ██  ██  ██" 
   info  "██      ██ ██   ██    ██    ██      ██v$UTILITY_VERSION"
   info "A utility for ricing up vanilla debian with your personal dwm setup"
}


pre_run_check(){
    if [[ -z "$BASH" ]]; then
        error "$0 only works in BASH, quitting!" "exit-after"
    fi
    
    if [[ "$OSTYPE" != "linux-gnu" ]];then
        error "Unsupported System!, quitting!" "exit-after"
    fi
    

    local distribution_id
    local distribution
    distribution_id=$(cat /etc/*-release | grep -w "ID")
    distribution="${distribution_id:3}"
    if [[ "$distribution" != "debian" ]];then
        warning "Non-debian system detected!. Platforms other than Debian are Untested!. continuing..."
        sleep 1.5
    fi
}

check_dependencies(){ 
   for dep in "${UTILITY_DEPS[@]}"; do
       if [[ ! $(command -v "$dep") ]]; then
           error "$dep not found, quitting!" "exit-after"
        fi
   done
}

sync_apt_repo(){
    info "Syncing apt with remote repos" "log"
    info "Invoking su user..."
    su -c "yes | apt update" > /dev/null
    local ret_code=$?
    if [[ $ret_code -eq 1 ]];then
        error "error logging to su user, quitting" "exit-after" 
    elif [[ $ret_code -ne 0 ]]; then
        error " \`apt update\` failed, possibly due to: "
        error "1: No root access"
        error "2: Network failure"
        error "3: Malformed mirrorlist / Mirror down"
        error "Resolve this issue manually and then continue, quitting!" "exit-after"
    fi
}

install_n_configure_sudo(){
    local user_name
    user_name=$(whoami)
    printf "Is sudo avaliable?: "
    if [[ $(command -v sudo) ]]; then
        printf "\x1b[32mYES\x1b[\n"
        return
    else
        printf "\x1b[31mNO\x1b[m\n"
    fi
    read -r -n1 -p "Do you want me to try to automatically install and configure sudo [Y/N] " opt
    case $opt in
        Y | y | yes)
            # using true as nop.
            # YES i don't know a better way
           true 
        ;;
        *)
            info "script interrupted!. install/configure sudo manually and continue."
            info "Note: you may create $HOME/.MHYM_RESUME_STATE to resume the script after this step."
            info "quitting!"
            exit 0
        ;;
    esac
    printf "\n"
    info "Installing sudo for $user_name" "log"
    info "Invoking su user..." "log"
    su  -c "yes | apt install sudo" > /dev/null
    local ret_code=$?
    if [[ $ret_code -eq 1 ]];then
        error "error logging to su user, quitting" "exit-after"

    elif [[ $ret_code -ne 0 ]]; then
        
        error "error occured while installing sudo\nReason: \nnon-zero return-code returned\nRET CODE: $ret_code\nresolve manually and continue, quitting" "exit-after"
    fi
    info "Adding $user_name to sudo group"
    su -c "/sbin/usermod -aG sudo $user_name> /dev/null" > /dev/null
    local ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        error "Failed adding \`$user_name\` to sudo group. resolve manually and continue, quitting!" "exit-after"
    fi
    touch "$HOME/.MHYM_RESUME_STATE"
    info "User \`$user_name\` has been added to sudo group"
    info "a re-login is required for effect. the script will resume on re-run at current state."
    exit 0
}

install_dwm_deps(){
    info "Installing DWM Dependencies..."
    info "It may take a while... Dont do unnecessary inputs"
    yes | sudo apt install "${DWM_DEP_PACKAGES[@]}" > /dev/null
    local ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        local package_list="${DWM_DEP_PACKAGES[*]}"
        error "error while installing required dwm dependencies"
        error "packages include: $package_list"
        error "resolve these manually and continue, quitting!" "exit-after"
    fi
}

__get_repo_name(){
    local uri=$1
    local uri_reversed
    uri_reversed="$(echo "$uri" | rev)"
    OIFS=$IFS
    IFS="/"
    read -r repo_name_rev _tmp <<< "$uri_reversed"
    IFS=$OIFS
    local endswith_dot_git=true
    if [[ ! "${repo_name_rev:0:4}" = "tig." ]];then
        endswith_dot_git=false
    fi 
    local repo_name
    repo_name="$(echo "$repo_name_rev" | rev)"
    if [[ $endswith_dot_git = true ]]; then
        printf "%s" "${repo_name:0:-4}"
    else

        printf "%s" "$repo_name"
    fi
}


git_clone_repo(){
    local repo_uri=$1
    git clone "$repo_uri" > /dev/null
    local ret_code
    ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        error "error cloning remote repository at $repo_uri. resolve manually and continue, quitting!" "exit-after"
    fi
}

__analyze_uri(){
    local uri=$1
    local reverse_uri
    reverse_uri="$(echo "$uri" | rev)"
    if [[ "${uri:0:4}" = "file" ]]; then
        printf "local"
    elif [[ "${uri:0:4}" = "http" ]] && [[ "${reverse_uri:0:4}" = "tig." ]] || [[ "${uri:8:3}" = "git" ]]; then
        printf "remote-git"
    elif [[ "${uri:0:4}" = "http" ]]; then
        printf "remote"
    else 
        printf "invalid"
    fi
}

readline_prompt(){
    local prompt_str=$1
    local out_varname=$2
    read -r -e -p "$prompt_str" prompt_input 
    printf -v "$out_varname" "%s" "$prompt_input"
}

install_n_configure_dwm(){
    info "Installing DWM..." "log" 
    local CWD="$PWD"
    cd /tmp
    if [[ -z "$DWM_URI" ]]; then
        if [[ $NO_PROMPT = true ]]; then
            error "cannot be NO_PROMPT with partial options set, quitting!" "exit-after"
        fi
    readline_prompt "[DWM URI]: " DWM_URI
    fi


    local repo_type
    repo_type="$(__analyze_uri "$DWM_URI")"
    
    if [[ "$repo_type" = "invalid" ]];then
        error "invalid uri. please give a valid git http/file uri, quitting!" "exit-after"
    
    elif [[ "$repo_type" = "remote-git" ]];then
        local repo_name
        repo_name="$(__get_repo_name "$DWM_URI")"
        git_clone_repo "$DWM_URI"
        cd "./$repo_name"
    
    elif [[ "$repo_type" = "local" ]];then
        # truncate the file:// scheme
        DWM_URI="${DWM_URI:7}" 
        cd "$DWM_URI"
    
     else
        warning "uri assertion has failed , report this issue!"
        error "Invalid uri. quitting!..." "exit-after" 
    fi
    
    info "requesting sudo access..." "log"
    local null_redirect=""
    if [[ $NO_PROMPT = true ]]; then
        null_redirect=" > /dev/null"
    else 
        info "showing catalog of make commands for dwm build..." "log"
    fi
    # shellcheck disable=SC2086
    sudo $DWM_MAKE_CMD $null_redirect
    local ret_code
    ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        error " \` make install\` failed. resolve that manually and continue, quitting!" "exit-after"
    fi 
    make clean >/dev/null
    cd "$CWD"
}

install_n_configure_dmenu(){
    info "Installing DMENU..." "log" 
    local CWD="$PWD"
    cd /tmp
    if [[ -z "$DMENU_URI" ]]; then
        readline_prompt "[DMENU URI]: " DMENU_URI
    fi
    local repo_type
    repo_type="$(__analyze_uri "$DMENU_URI")"
    
    if [[ $repo_type = "invalid" ]];then
        error "invalid uri. please give a valid git http/file uri, quitting!" "exit-after"
    
    elif [[ $repo_type = "local" ]]; then
        local truncted_filepath=${DMENU_URI:7}
        cd "$truncted_filepath"
    
    elif [[ $repo_type = "remote-git" ]];then
        git_clone_repo "$DMENU_URI"
        local repo_name
        repo_name="$(__get_repo_name "$DMENU_URI")"
        cd "$repo_name"
    
    else
        warning "got $repo_type as repository type, which was not expected!"
        warning "uri assertion has failed , report this issue!"
        error "Invalid uri. quitting!..." "exit-after"
    fi

    info "requesting sudo access..." "log"
    local null_redirect=""
    if [[ $NO_PROMPT = true ]]; then
        null_redirect=" > /dev/null"
    else 
        info "showing catalog of make commands for dmenu build..." "log"
    fi 
    # shellcheck disable=SC2086
    sudo $DMENU_MAKE_CMD $null_redirect
    local ret_code
    ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        error " \`make install\` failed. resolve that manually and continue, quitting!" "exit-after"
    fi
    make clean > /dev/null
    cd "$CWD"
}

install_n_configure_dwmbar(){
    local CWD=$PWD
    cd /tmp
    info "Installing DWMBAR..." "log"
    if [[ "$DWMBAR_URI" = "nill" ]]; then
        return
    fi
    if [[ -z $DWMBAR_URI ]];then
        readline_prompt "[DWMBAR URI]: " DWMBAR_URI
    fi
    local repo_type
    repo_type="$(__analyze_uri "$DWMBAR_URI")"
    
    if [[ "$repo_type" = "remote-git" ]]; then
        local repo_name
        repo_name="$(__get_repo_name "$DWMBAR_URI")"
        git clone "$DWMBAR_URI"
        cd "$repo_name"
    elif [[ "$repo_type" = "local" ]];then
        DWMBAR_URI=${DWMBAR_URI:7}
        cd "$DWMBAR_URI"
    elif [[ "$repo_type" = "invalid" ]]; then
        error "invalid uri. please give a valid git http/file uri, quitting!" "exit-after"
    fi
    info "request sudo access..." "log"
    
    local null_redirect=""
    if [[ $NO_PROMPT = true ]];then
        null_redirect="> /dev/null"
    fi
    # shellcheck disable=SC2086
    sudo ./install.sh $null_redirect
    
    cd "$CWD"
}

install_n_configure_terminal_emulator(){
    # ig, for now we just install the relevant package
    yes | sudo apt install $TERMINAL_PKG
    local ret_code
    ret_code=$?
    if [[ $ret_code -ne 0 ]]; then
        warning "error while installing \`$TERMINAL_PKG\` terminal emulator package. Please install it manually afterwards..."
    fi
}

setup_post_install_packages(){
    info "installing post-install system-packages" "log"
    info "following packages will be installed:"
    info "${POST_INSTALL_SYSTEM_PACAGES[*]}"
    yes | sudo apt install "${POST_INSTALL_SYSTEM_PACAGES[@]}" > /dev/null
    local ret_code=$?
    if [[ $ret_code -ne 0 ]];then
    	warning "system packages installation failed, continuing!"
    fi
}



set_xinitrc() {
    if [[ -z "$BACKGROUND_URI" ]];then
        readline_prompt "[BACKGROUND_URI]: " out
        # shellcheck disable=SC2154
        BACKGROUND_URI="$out" 
    fi
    
    local bg_path
    local bg_type
    bg_type="$(__analyze_uri "$BACKGROUND_URI")"
    local file_name 
    if [[ "$bg_type" = "local" ]];then
        bg_path=${BACKGROUND_URI:7}
    elif [[ "$bg_type" = "remote" ]];then
        file_name="$(basename "$BACKGROUND_URI")" 
        wget "$BACKGROUND_URI" -O "$HOME/$file_name"
        bg_path="$HOME/$file_name"
    elif [[ "$bg_type" = "invalid" ]];then
        error "invalid uri. please give a valid http/file uri, quitting!" "exit-after"
    else
        warning "got $repo_type as repository type, which was not expected!"
        warning "uri assertion has failed , report this issue!"
        error "Invalid uri. quitting!..." "exit-after"
    fi
    local xresources_cmd=""
    local setbg_cmd="$BG_UTIL $UTIL_CMD $bg_path" 
    
    if [[ $out = "nill" ]];then
        setbg_cmd="" 
    fi

    if [[ $OVERWRITE_XRESOURCES = true ]]; then
        if [[ -z $DOTXRESOURCES_PATH ]];then
            error "need path for .Xresources. quitting!" "exit-after"
        fi
        xresources_cmd="xrdb $DOTXRESOURCES_PATH"
    elif [[ $MERGE_XRESOURCES = true ]]; then
        if [[ -z $DOTXRESOURCES_PATH ]];then
            error "need path for .Xresources. quitting!" "exit-after"
        fi 
        xresources_cmd="xrdb -merge $DOTXRESOURCES_PATH" 
    fi
    
    cat > "$HOME/.xinitrc" << EOT
# .xinitrc generated by mhym
$xresources_cmd
$setbg_cmd
exec dwmbar &
exec dwm 
EOT
    if [[ $EXEC_AT_LOGIN = true ]]; then
        # shellcheck disable=SC2140
        echo "[ -z "\$DISPLAY" ] && [ "\$XDG_VTNR" = 1 ] && exec startx" >> "$HOME/.bash_profile"
    fi

    # since the current user is put in sudoers file. put /sbin to PATH
    echo "PATH=$PATH:/sbin" >> "$HOME"/.bashrc
}



clean_up_n_exit(){
    # clean up and exit
    info "Doing post cleanup..."
    rm "$HOME/.MHYM_RESUME_STATE"
    rm -rf /tmp/dwm* 
    rm -rf /tmp/dmenu*
    info "mhym has performed all the personalizations." "log"
    info "Re-login to start your dwm session"
    exit 0
}

if [[ $NO_PROMPT != true ]];then
    logo_print
fi

# if in a resumed state, skip to post sudo install
if [ -e "$HOME/.MHYM_RESUME_STATE" ]; then
    info "Resuming state after \`sudo\` install..." "log"
    install_dwm_deps
    install_n_configure_dwm
    install_n_configure_dmenu
    install_n_configure_dwmbar
    install_n_configure_terminal_emulator
    setup_post_install_packages
    set_xinitrc
    clean_up_n_exit
fi


pre_run_check
check_dependencies
sync_apt_repo
install_n_configure_sudo
install_dwm_deps
install_n_configure_dwm
install_n_configure_dmenu
install_n_configure_dwmbar
install_n_configure_terminal_emulator
setup_post_install_packages
set_xinitrc
clean_up_n_exit
